project:
  type: website

website:
  title: "Miguel González"
  navbar:
    right:
      - icon: github
        href: https://github.com/MiguelPuntoEs/
      - icon: linkedin
        href: http://linkedin.com/in/mgcalvo/
format:
  html:
    theme: cosmo
