---
title: "Economic information sources"
---

Central banks:

- [FRED](https://fred.stlouisfed.org) (Federal Reserve Economic Data)
- [ECB](https://www.ecb.europa.eu/stats/macroeconomic_and_sectoral/hicp/html/index.en.html). European Central Bank.
- [Deutsche Bundesbank](https://www.bundesbank.de/en/statistics)
- [Bank of England](https://www.bankofengland.co.uk/statistics)
- [Swiss National Bank](https://data.snb.ch/)
- [Banco de España](https://www.bde.es/webbe/es/estadisticas/otras-estadisticas/historicas/index.html)
- [Banco de Guatemala](https://www.banguat.gob.gt)
- [Bank of Japan](https://www.boj.or.jp/en/statistics/index.htm)

Statistic bureaux:

- [U.S. Bureau of Labor Statistics](https://www.bls.gov) (BLS)
- [Office for National Statistics](https://www.ons.gov.uk) (UK)
- [Statistisches Bundesamt](https://www.destatis.de)
- [INE](https://www.ine.es) (Instituto Nacional de Estadística)
- [Bundesamt für Statistik](https://www.bfs.admin.ch/)
- [Statistics of Japan e-Stat](https://www.e-stat.go.jp/en)

International data:

- [World Bank](https://datos.bancomundial.org)
- [Eurostat](https://ec.europa.eu/eurostat)
- [CEPALSTAT](https://statistics.cepal.org/portal/cepalstat/index.html?lang=es) (Comisión Económica para América Latina y el Caribe)
- [OECD](https://data.oecd.org) (Organisation for Economic Co-operation and Development)
- [OPEC](https://asb.opec.org/data/ASB_Data.php) (Organization of the Petroleum Exporting Countries)
- [International Labour Organization](https://www.ilo.org/ilostat-files/Documents/SDMX_User_Guide.pdf) (ILOSTAT)
- [UN Comtrade](https://comtradeplus.un.org)
- [IEA](https://www.iea.org/data-and-statistics/data-sets) (International Energy Agency)
- Kauffman Foundation
- Pew Research
- [European Social Survey](https://www.europeansocialsurvey.org)
- [IMF](https://data.imf.org) (International Monetary Fund)
- [Bruegel](https://www.bruegel.org/datasets) (e.g. [real effective exchange rates](https://www.bruegel.org/publications/datasets/real-effective-exchange-rates-for-178-countries-a-new-database))
- [Penn World Table](https://www.rug.nl/ggdc/productivity/pwt/?lang=en)

US statistics:

- [Federal Deposit Insurance Corp](https://www.fdic.gov/bank/statistical/)
- [American Community Survey](https://www.census.gov/programs-surveys/acs) (ACS)
- [US Census Bureau](https://www.census.gov/data/developers/data-sets/international-trade.html) - Trade
- Energy Information Administration (EIA), e.g. [Petroleum Price](https://www.eia.gov/dnav/pet/hist/rbrteA.htm)
- [Bureau of Economic Analysis](https://apps.bea.gov/API/bea_web_service_api_user_guide.htm) (BEA)
- SEC [EDGAR database](http://www.sec.gov/edgar/searchedgar/companysearch.html), e.g. shares outstanding ([10-Q/K](https://quant.stackexchange.com/questions/4079/data-source-for-historical-share-outstanding-totals-for-individual-stocks))
- [Shadow Government Statistics](http://www.shadowstats.com/)

Historical statistics:

- [Economic History Association](https://eh.net)
- [Estadísticas históricas de España. Siglos XIX-XX](https://www.fbbva.es/wp-content/uploads/2017/05/dat/DE_2006_estadisticas_historicas.pdf). Albert Carreras and Xavier Tafunell. Fundación BBVA.
- [Maddison Project](https://www.rug.nl/ggdc/historicaldevelopment/maddison/?lang=en)

Agricultural data:

- EU: [Agri-food data portal](https://agridata.ec.europa.eu/extensions/DataPortal/API_Documentation.html), [EEX](https://www.eex.com/en/market-data/agriculturals/futures)
- US: Foreign Agricultural Service ([FAS](https://fas.usda.gov/data)). Global interface: [OpendataWeb (usda.gov)](https://apps.fas.usda.gov/opendatawebV2/#/)
    - Production, Suppy & Distribution ([PS&D](https://apps.fas.usda.gov/psdonline/app/index.html#/app/about))

Treasuries:

- [Daily Treasury Par Yield Curve Rates](https://home.treasury.gov/resource-center/data-chart-center/interest-rates/TextView?type=daily_treasury_yield_curve&field_tdr_date_value=2023) (US Department of the Treasury)
- US Treasury [Monthly Treasury Statement](https://fiscaldata.treasury.gov/datasets/monthly-treasury-statement/summary-of-receipts-and-outlays-of-the-u-s-government)

Finance:

- [Yahoo Finance](https://finance.yahoo.com)

Others:

- [Statista](https://www.statista.com)
- [Datahub](https://datahub.io)
- [CME FedWatch Tool](https://www.cmegroup.com/markets/interest-rates/cme-fedwatch-tool.html)
- [Bloomberg World Interest Rate Probability](https://www.bloomberg.com/professional/blog/fed-to-cut-u-s-rates-next-in-september-2020-futures-indicate/) (también para Eurozona)
- [OEC](https://oec.world/es): international trade
- [Trading Economics](https://tradingeconomics.com/)

Interesting indicators and reports:

- Human Development Index (HDI)
- Social Progress Index (SPI)
- [Freedom in the World](https://freedomhouse.org/report/freedom-world) from Freedom House.
- [World Happiness Report](https://worldhappiness.report)
- World Governance Index
- [Worldwide Governance Indicators](https://www.worldbank.org/en/publication/worldwide-governance-indicators). World Bank
- [Index of Economic Freedom](https://www.heritage.org/index/). Heritage Foundation 
- [Big Mac Index](https://www.economist.com/interactive/big-mac-index). The Economist
- [Office of Financial Research](https://www.financialresearch.gov/money-market-funds/federal-reserve-repo-facility-total-utilization-and-mmfs-participation/)
- [Producer Price Index](https://www.bls.gov/ppi/)

Interest rates:

- [EFFR](https://fred.stlouisfed.org/series/EFFR) Effective Federal Funds Rate
- [Key ECB interest rates](https://www.ecb.europa.eu/stats/policy_and_exchange_rates/key_ecb_interest_rates/html/index.en.html)
