---
title: "Python Resources"
---

Python [official documentation](https://docs.python.org/)

## Libraries

### General purpose

Dependency management:

- [uv](https://github.com/astral-sh/uv)
- [Poetry](https://python-poetry.org)

Plots:

- [Matplotlib](https://matplotlib.org/)
- [Plotly](https://plotly.com/python/)
- [Seaborn](https://seaborn.pydata.org/)
- [Altair](https://altair-viz.github.io/)

APIs:

- [Django](https://www.djangoproject.com/)
- [FastAPI](https://fastapi.tiangolo.com/)
- [Flask](https://flask.palletsprojects.com/)

Time series:

- [Darts](https://github.com/unit8co/darts)
- [sktime](https://github.com/sktime/sktime)
- [Merlion](https://github.com/salesforce/Merlion) (Salesforce)
- [Kats](https://facebookresearch.github.io/Kats/) (Facebook)
- [Greykite](https://github.com/linkedin/greykite) (LinkedIn)
- [PyEMMA](http://emma-project.org/latest/)
- [Deeptime](https://deeptime-ml.github.io/latest/index.html)
- [statsmodels](https://www.statsmodels.org/stable/index.html): built-in ARIMA, STL…

Data processing:

- [Pandas](https://pandas.pydata.org)
- [Polars](https://pola.rs)
- [Ibis](https://ibis-project.org/)
- [dbt](https://www.getdbt.com/)
- PySpark

Dashboards:

- [Dash](https://dash.plotly.com/)
- [Streamlit](https://streamlit.io/)
    - [Streamlit Authenticator](https://github.com/mkhorasani/Streamlit-Authenticator)

Other:

- [httpx](https://www.python-httpx.org)
- [Pydantic](https://docs.pydantic.dev/latest/)
- [Quarto](https://quarto.org/docs/guide/)
- [AutoGluon](https://auto.gluon.ai/stable/index.html)
- [mypy](https://mypy-lang.org/): Static typing
- [nbQA](https://github.com/nbQA-dev/nbQA): quality assurance
- [Flake8](https://flake8.pycqa.org/en/latest/): style guide enforcement
- [Poetry](https://python-poetry.org/): dependency management
- [Joblib](https://joblib.readthedocs.io/en/stable/): running pipelines, memory management
- [decimal](https://docs.python.org/3/library/decimal.html)
- Pendulum
- PyPDF
- Icecream: debugging
- Loguru 
- Rich: rich output to terminal
- Argparse
- Tqdm
- Xarray
- Result
- Sqlmodel
- SQLAlchemy
- BeautifulSoup
- SymPy
- Cookiecutter
- Pickle
- Pygame
- Missingno
- Jinja2
- Watchdog: file system changes
- Returns
- Numerizer
- Box
- pipe
- Nicegui
- Screenshot-to-code


### AI-related

Machine learning:

- [scikit-learn](https://scikit-learn.org/)

Deep learning:

- [PyTorch](https://pytorch.org)
- [Keras](https://keras.io)
- [TensorFlow](https://www.tensorflow.org)

Hyperparameter tuning:

- [Ray Tune](https://docs.ray.io/en/latest/tune/index.html)
- [Katib](https://www.kubeflow.org/docs/components/katib/overview/)
- [Optuna](https://optuna.org/)
- [TensorBoard](https://www.tensorflow.org/tensorboard)

## Books

- Fluent Python
- Clean Architectures in Python
- Architecture Patterns with Python
- High Performance Python
- CPython Internals
- Python Distilled


## Websites

- [Pydon'ts](https://mathspp.com/blog/pydonts)