---
title: "Taller de Python en UFM Madrid"
---

Viernes 25 de abril de 2025, 16:00-21:00.

## Materiales

Ver material de apoyo en [página principal](../index.qmd).

Repositorio de código en [GitHub](https://github.com/MiguelPuntoEs/python-ufm).

## Contenidos

- Introducción a Python
    - Instalación e introducción a Visual Studio Code
    - Instalación y configuración básica (Google Colab / Jupyter Notebook)
    - Breve repaso de sintaxis básica: variables, operaciones matemáticas, estructuras de control
- Manejo de datos económicos con Pandas:
    - Introducción a Pandas: lectura y manipulación de datos
    - Importación de datos económicos desde archivos CSV y Excel
    - Análisis exploratorio de datos: introducción a Matplotlib/Plotly y generación de gráficos para revistas académicas.
- Estadística y econometría en Python:
    - Estadística descriptiva con NumPy y Pandas
    - Introducción a modelos econométricos con Statsmodels
    - Regresión lineal aplicada a datos económicos
    - Posibilidades de Statsmodels para modelos más avanzados (beta regression, Markov switching models…)
- APIs para datos económicos
    - Obtener datos en tiempo real de fuentes como el Banco Mundial o el BCE
    - API de la Fed
    - Portales estadísticos (Eurostat, INE…)
- Machine Learning para predicción económica
    - Introducción al Machine Learning en economía
    - Predicción de series temporales con Scikit-Learn
    - Uso de modelos como ARIMA y Random Forest
    - Modelos avanzados (transformadores, darts, regresión armónica…)
- Comparte tu trabajo:
    - Dashboards (dash)
    - Páginas web, notebooks, presentaciones (quarto)
- Prototipado de interfaces API
    - Backend con Django
    - Prototipo con Nuxt
- IA en desarrrollo
    - Coding con IA: GitHub Copilot
    - Vibe coding: Cursor